before_script:
  - git config --global http.proxy "http://proxy-us.intel.com:911"
  - git config --global https.proxy "http://proxy-us.intel.com:911"
  - git config --global http."https://gitlab.devtools.intel.com".proxy ""
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.devtools.intel.com".insteadOf "https://gitlab.devtools.intel.com"
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - cd $CI_PROJECT_DIR

variables:
  http_proxy: http://proxy-us.intel.com:911
  https_proxy: http://proxy-us.intel.com:911
  HTTP_PROXY: http://proxy-us.intel.com:911
  HTTPS_PROXY: http://proxy-us.intel.com:911
  no_proxy: ".intel.com"
  DOCKER_GRAPHDRIVER: secureoverlay2

stages:
 - build
 - test

build:
  stage: build
  tags: 
    - secdocker
  cache:
    paths:
    - $CI_PROJECT_DIR

  script:
  - cd $CI_PROJECT_DIR
  - make

TestCLI:
  stage: test
  tags: 
    - secdocker
  script:
  - cd $CI_PROJECT_DIR
  - make -C docker-ce/components/cli test
  
TestUnitEngine:
  stage: test
  tags: 
    - secdocker
  script:
  - cd $CI_PROJECT_DIR
  - make -C docker-ce/components/engine test-unit
  
TestIntegrationEngine:
  stage: test
  tags: 
    - secdocker
  script:
    - cd $CI_PROJECT_DIR
    - make -C docker-ce/components/engine test-integration
