---
stages:
  - build
  - test

variables:
  DOCKER_GRAPHDRIVER: secureoverlay2
  HTTPS_PROXY: ""
  HTTP_PROXY: ""
  NO_PROXY: "127.0.0.1,localhost,0.0.0.0,reg-name.io"
  http_proxy: ""
  https_proxy: ""
  no_proxy: "127.0.0.1,localhost,reg-name.io"

cache:
  paths:
    - docker-ce/

build:
  artifacts:
    paths:
      - out/
    expire_in: 1 week
  script:
    - "cd $CI_PROJECT_DIR"
    - "make all"
  stage: build
  tags:
    - secdocker

TestEngine:
  artifacts:
    paths:
      - docker-ce/components/engine/bundles/test-integration/test.log
      - docker-ce/components/engine/bundles/test-integration/docker.log
  script:
    - "make unittest"
    - "make testintegrationengine"
  stage: test
  tags:
    - secdocker
  dependencies:
    - build
