---
stages:
  - build
  - test

variables:
  DOCKER_GRAPHDRIVER: secureoverlay2
  HTTPS_PROXY: "${HTTPS_PROXY}"
  HTTP_PROXY: "${HTTP_PROXY}"
  NO_PROXY: "${NO_PROXY}"
  http_proxy: "${HTTP_PROXY}"
  https_proxy: "${HTTPS_PROXY}"
  no_proxy: "${NO_PROXY}"

cache:
  paths:
    - docker-ce/

build:
  artifacts:
    paths:
      - out/
    expire_in: 1 week
  script:
    - "cd $CI_PROJECT_DIR"
    - "make all"
  stage: build
  tags:
    - secdocker

TestEngine:
  artifacts:
    paths:
      - docker-ce/components/engine/bundles/test-integration/test.log
      - docker-ce/components/engine/bundles/test-integration/docker.log
  script:
    - "make unittest"
    - "make testintegrationengine"
  stage: test
  tags:
    - secdocker
  dependencies:
    - build
