--- 
TestCLI: 
  script: 
    - "cd $CI_PROJECT_DIR"
    - "make testcli"
  stage: test
  tags: 
    - secdocker
TestIntegrationEngine: 
  script: 
    - "cd $CI_PROJECT_DIR"
    - "make testintegrationengine"
  stage: test
  tags: 
    - secdocker
TestUnitEngine: 
  script: 
    - "cd $CI_PROJECT_DIR"
    - "make testunitengine"
  stage: test
  tags: 
    - secdocker
before_script: 
  - "git config --global http.proxy \"http://proxy-us.intel.com:911\""
  - "git config --global https.proxy \"http://proxy-us.intel.com:911\""
  - "git config --global http.\"https://gitlab.devtools.intel.com\".proxy \"\""
  - "git config --global url.\"https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.devtools.intel.com\".insteadOf \"https://gitlab.devtools.intel.com\""
  - "mkdir -p ~/.ssh"
  - "chmod 700 ~/.ssh"
  - "cd $CI_PROJECT_DIR"
build: 
  cache: 
    paths: 
      - $CI_PROJECT_DIR
  script: 
    - "cd $CI_PROJECT_DIR"
    - "make clean build"
  stage: build
  tags: 
    - secdocker
stages: 
  - build
  - test
variables: 
  DOCKER_GRAPHDRIVER: secureoverlay2
  GIT_CLEAN_FLAGS: none
  HTTPS_PROXY: "http://proxy-us.intel.com:911"
  HTTP_PROXY: "http://proxy-us.intel.com:911"
  NO_PROXY: "127.0.0.1,localhost,0.0.0.0,reg-name.io"
  http_proxy: "http://proxy-us.intel.com:911"
  https_proxy: "http://proxy-us.intel.com:911"
  no_proxy: ".intel.com,172.,127.0.0.1,localhost,reg-name.io"

