FROM    golang:1.12.5-alpine

ENV http_proxy "http://10.1.192.48:911"
ENV https_proxy "http://10.1.192.48:911"

RUN     apk add -U git bash coreutils gcc musl-dev

ENV     CGO_ENABLED=0 \
        DISABLE_WARN_OUTSIDE_CONTAINER=1
WORKDIR /go/src/github.com/docker/cli
CMD     ./scripts/build/binary
